package _guesstheword;

//@author Abdalhadi Al-shehri || 443004342

import java.awt.Color;
import java.util.List;

public class GuessTheWord extends javax.swing.JFrame {

    int positionX=0 , positionY=0;  //
    static int right = 0; // counter for the score
    static int wrong = 0; // counter for the score
    int index = 0; // what word did the user reach
    public static int NumOfWords; // number of words to guess
    public List<String> ChosenW; // List for chosen words

    public GuessTheWord(int numOfWords) {// Creates new form GuessTheWord
        NumOfWords = numOfWords;
        initComponents();
        setLocationRelativeTo(null);
        setChosenW();
    }

    public void setChosenW() { // to save the words in the list from the method in wordBank Class
        WordBank WDobj = new WordBank(NumOfWords);
        ChosenW = WDobj.getChosenWords();
    }

    public void displayWord() { // display word with missing letters in the Jlable

        // get random position
        int pos1 = (int) ((Math.random()) * (ChosenW.get(index).length()));
        int pos2 = (int) ((Math.random()) * (ChosenW.get(index).length()));

        // set '_' at random positions
        StringBuilder newtext = new StringBuilder(ChosenW.get(index));
        newtext.setCharAt(pos1, '_');
        newtext.setCharAt(pos2, '_');

        // set text to the jlabel
        jLabel_Word.setText(newtext.toString());

    }

    // checks if the word is right then adds to the wrong or right counter
    public void CheckWord() { // and if its the last word then after the check ,show score
        if (index == ChosenW.size() - 1) {
            if (jTextField_Guess.getText().equalsIgnoreCase(ChosenW.get(index))) {
                right++;
                jButton2.setEnabled(false);
                jButton1.setEnabled(true);
                Result R = new Result();
                R.ChangeText();
                R.setVisible(true);
                jLabel_Result.setText("Correct");
                jLabel_Result.setBackground(Color.green);
            } else {
                wrong++;
                jButton2.setEnabled(false);
                jButton1.setEnabled(true);
                jButton2.setEnabled(false);
                Result R = new Result();
                R.ChangeText();
                R.setVisible(true);
                jLabel_Result.setText("Wrong");
                jLabel_Result.setBackground(Color.red);
            }
        } else {
            if (jTextField_Guess.getText().equalsIgnoreCase(ChosenW.get(index))) {
                jLabel_Result.setText("Correct");
                jLabel_Result.setBackground(Color.green);
                right++;
            } else {
                jLabel_Result.setText("Wrong");
                jLabel_Result.setBackground(Color.red);
                wrong++;
            }

        }
        jTextField_Guess.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_Word = new javax.swing.JLabel();
        jLabel_Result = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField_Guess = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel_Word.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_Word.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel_Word.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Word.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Word.setText("Word");
        jLabel_Word.setOpaque(true);

        jLabel_Result.setBackground(new java.awt.Color(102, 102, 102));
        jLabel_Result.setFont(new java.awt.Font("Segoe UI", 0, 34)); // NOI18N
        jLabel_Result.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Result.setText("Result");
        jLabel_Result.setOpaque(true);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton2.setText("Next");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton3.setText("->");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        jTextField_Guess.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Guess.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField_Guess.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Guess.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Guess.setText("Guess");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(389, 389, 389)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel_Word, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel_Result, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(jTextField_Guess)))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jLabel_Word, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jTextField_Guess, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel_Result, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //if pressed get X and Y coordinates values
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        positionX = evt.getX();
        positionY = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    //if dragged set Jframe location
    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        setLocation(evt.getXOnScreen()-positionX, evt.getYOnScreen()-positionY);
    }//GEN-LAST:event_jPanel2MouseDragged

    // Start the game
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        index = 0;
        wrong = 0;
        right = 0;
        jTextField_Guess.setText("");
        jButton1.setEnabled(false);
        jButton2.setEnabled(true);
        jTextField_Guess.setEditable(true);
        jLabel_Result.setText("Result");
        jLabel_Result.setBackground(new java.awt.Color(102, 102, 102));
        displayWord();
    }// GEN-LAST:event_jButton1ActionPerformed

    // next button it checks the word and display another word only if its not the
    // last word
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed

        CheckWord();
        if (index < ChosenW.size() - 1) {
            index++;
            displayWord();
        }

    }// GEN-LAST:event_jButton2ActionPerformed

    // return the user to the game menu and close this Jframe
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
        Menu MM = new Menu();
        MM.setVisible(true);
        dispose();
    }// GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel_Result;
    private javax.swing.JLabel jLabel_Word;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField_Guess;
    // End of variables declaration//GEN-END:variables
}
